version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-server
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
